import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Metehan Günaydın",
  description: "Generated by CodeLiq member Metehan Günaydın.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="tr" className="bg-vscode-background text-vscode-textLight font-mono">
      <body>{children}</body>
    </html>
  );
}
